version: '3'
services:
  # dfdewey:
    # build:
      # context: ../
      # dockerfile: ./docker/Dockerfile
    # links:
      # - elasticsearch
      # - postgres
    # environment:
      # - POSTGRES_USER=dfdewey
      # - POSTGRES_PASSWORD=password
      # - POSTGRES_ADDRESS=postgres
      # - POSTGRES_PORT=5432
      # - ELASTIC_ADDRESS=elasticsearch
      # - ELASTIC_PORT=9200
    # restart: always

  elasticsearch:
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms32g -Xmx32g
    image: elasticsearch:7.4.0
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    restart: always

  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=dfdewey
      - POSTGRES_PASSWORD=password
    restart: always
